const STORAGE_KEY='attendanceData_v1_fixed_ids';
let page=1;
const $=id=>document.getElementById(id);
function genId(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9)}
function nowTimestamp(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`}
function loadData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch(e){return[]}}
function saveData(d){localStorage.setItem(STORAGE_KEY,JSON.stringify(d));updateDashboard()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function openApp(){ $('welcome').classList.add('hidden');$('app').classList.remove('hidden');$('todayText').textContent=new Date().toLocaleString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'});render();updateDashboard() }
function addAttendance(keep=false){const name=$('studentName').value.trim(),roll=$('rollNo').value.trim(),course=$('course').value.trim(),status=$('statusSelect').value;if(!name||!roll||!course){toast('Please fill all student details');return}const d=loadData();if(d.some(x=>x.roll.toLowerCase()===roll.toLowerCase()&&x.course.toLowerCase()===course.toLowerCase())){if(!confirm('A record with this roll number and course already exists. Add anyway?'))return}d.push({id:genId(),name,roll,course,status,time:nowTimestamp()});saveData(d);if(!keep){$('studentName').value='';$('rollNo').value='';$('course').value=''}toast('Attendance record added');render()}
function removeAttendance(id){if(!confirm('Delete this attendance record?'))return;saveData(loadData().filter(x=>x.id!==id));toast('Record deleted');render()}
function getFilters(){return{q:$('globalSearch')?.value.trim().toLowerCase()||'',name:$('filterName')?.value.trim().toLowerCase()||'',roll:$('filterRoll')?.value.trim().toLowerCase()||'',course:$('filterCourse')?.value.trim().toLowerCase()||'',status:$('filterStatus')?.value||''}}
function filteredData(){const f=getFilters();return loadData().filter(r=>(!f.q||[r.name,r.roll,r.course].some(v=>v.toLowerCase().includes(f.q)))&&(!f.name||r.name.toLowerCase().includes(f.name))&&(!f.roll||r.roll.toLowerCase().includes(f.roll))&&(!f.course||r.course.toLowerCase().includes(f.course))&&(!f.status||r.status===f.status))}
function render(){if(!$('attendanceTableBody'))return;const data=filteredData(),size=Number($('pageSize').value||10),pages=Math.max(1,Math.ceil(data.length/size));if(page>pages)page=pages;const start=(page-1)*size,rows=data.slice(start,start+size);$('attendanceTableBody').innerHTML=rows.length?rows.map(r=>`<tr><td><input type="checkbox" class="rowCheck" data-id="${r.id}"></td><td><strong>${esc(r.name)}</strong></td><td>${esc(r.roll)}</td><td>${esc(r.course)}</td><td><span class="status ${r.status}">${r.status==='present'?'Present':'Absent'}</span></td><td>${esc(r.time)}</td><td><div class="row-actions"><button class="mini edit" onclick="editAttendance('${r.id}')">Edit</button><button class="mini remove" onclick="removeAttendance('${r.id}')">Delete</button></div></td></tr>`).join(''):`<tr><td colspan="7" class="empty">No attendance records found.</td></tr>`;$('pageInfo').textContent=`Showing ${rows.length?start+1:0}–${Math.min(start+rows.length,data.length)} of ${data.length} records`;$('selectAll').checked=false;updateRecent()}
function changePage(n){page+=n;render()}
function toggleSelectAll(cb){document.querySelectorAll('.rowCheck').forEach(x=>x.checked=cb.checked)}
function selectedIds(){return[...document.querySelectorAll('.rowCheck:checked')].map(x=>x.dataset.id)}
function markSelected(status){const ids=selectedIds();if(!ids.length){toast('Select at least one row');return}const d=loadData();d.forEach(r=>{if(ids.includes(r.id)){r.status=status;r.time=nowTimestamp()}});saveData(d);toast(`${ids.length} record(s) updated`);render()}
function removeSelected(){const ids=selectedIds();if(!ids.length){toast('Select at least one row');return}if(!confirm(`Delete ${ids.length} selected record(s)?`))return;saveData(loadData().filter(r=>!ids.includes(r.id)));toast(`${ids.length} record(s) deleted`);render()}
function markAllVisiblePresent(){const ids=[...document.querySelectorAll('.rowCheck')].map(x=>x.dataset.id);if(!ids.length){toast('No visible records');return}const d=loadData();d.forEach(r=>{if(ids.includes(r.id))r.status='present'});saveData(d);toast('Visible records marked present');render()}
function editAttendance(id){const r=loadData().find(x=>x.id===id);if(!r)return;$('editId').value=id;$('editName').value=r.name;$('editRoll').value=r.roll;$('editCourse').value=r.course;$('editStatus').value=r.status;$('editModal').classList.remove('hidden')}
function closeEdit(){$('editModal').classList.add('hidden')}
function saveEdit(){const id=$('editId').value,d=loadData(),r=d.find(x=>x.id===id);if(!r)return;const name=$('editName').value.trim(),roll=$('editRoll').value.trim(),course=$('editCourse').value.trim();if(!name||!roll||!course){toast('All fields are required');return}Object.assign(r,{name,roll,course,status:$('editStatus').value,time:nowTimestamp()});saveData(d);closeEdit();toast('Record updated');render()}
function clearFilters(){['globalSearch','filterName','filterRoll','filterCourse'].forEach(id=>$(id).value='');$('filterStatus').value='';page=1;render()}
function focusAdd(){$('dashboard').classList.remove('hidden');$('records').classList.add('hidden');$('pageTitle').textContent='Attendance Dashboard';$('studentName').focus();$('addPanel').scrollIntoView({behavior:'smooth'})}
function showSection(section,btn){$('dashboard').classList.toggle('hidden',section!=='dashboard');$('records').classList.toggle('hidden',section!=='records');$('pageTitle').textContent=section==='records'?'Attendance Records':'Attendance Dashboard';document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');if(section==='records')render()}
function updateDashboard(){const d=loadData(),p=d.filter(x=>x.status==='present').length,a=d.length-p,rate=d.length?Math.round(p/d.length*100):0;$('totalStat').textContent=d.length;$('presentStat').textContent=p;$('absentStat').textContent=a;$('rateStat').textContent=rate+'%';$('presentSub').textContent=(d.length?Math.round(p/d.length*100):0)+'% of records';$('absentSub').textContent=(d.length?Math.round(a/d.length*100):0)+'% of records';const courses={};d.forEach(r=>{courses[r.course]??={p:0,t:0};courses[r.course].t++;if(r.status==='present')courses[r.course].p++});$('courseStats').innerHTML=Object.keys(courses).length?Object.entries(courses).sort((a,b)=>b[1].t-a[1].t).slice(0,8).map(([c,v])=>{const pct=Math.round(v.p/v.t*100);return `<div class="chart-row"><span title="${esc(c)}">${esc(c.length>16?c.slice(0,16)+'…':c)}</span><div class="bar"><span style="width:${pct}%"></span></div><strong>${pct}%</strong></div>`}).join(''):'<div class="empty">Add records to see course statistics.</div>';updateRecent()}
function updateRecent(){const d=loadData().slice(-5).reverse();$('recentRecords').innerHTML=d.length?d.map(r=>`<div style="display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid var(--border)"><div><strong>${esc(r.name)}</strong><div class="muted">${esc(r.roll)} · ${esc(r.course)}</div></div><span class="status ${r.status}">${r.status}</span></div>`).join(''):'<div class="empty">No records yet.</div>'}
function clearAll(){if(!loadData().length){toast('No data to clear');return}if(confirm('This will permanently delete all attendance records from this browser. Continue?')){localStorage.removeItem(STORAGE_KEY);page=1;render();updateDashboard();toast('All attendance data cleared')}}
function exportExcel(){const d=loadData();if(!d.length){toast('No data to export');return}const rows=d.map(r=>({Name:r.name,'Roll No.':r.roll,Course:r.course,Status:r.status,'Date & Time':r.time}));const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Attendance');XLSX.writeFile(wb,`PGDAV_Attendance_${new Date().toISOString().slice(0,10)}.xlsx`);toast('Excel exported')}
function exportPDF(){const d=loadData();if(!d.length){toast('No data to export');return}const {jsPDF}=window.jspdf,doc=new jsPDF('l','pt','a4'),p=d.filter(x=>x.status==='present').length;doc.setFontSize(18);doc.text('PGDAV College - Attendance Report',40,40);doc.setFontSize(10);doc.text(`Generated: ${nowTimestamp()}   |   Total: ${d.length}   |   Present: ${p}   |   Absent: ${d.length-p}`,40,58);doc.autoTable({startY:75,head:[['Name','Roll No.','Course','Status','Date & Time']],body:d.map(r=>[r.name,r.roll,r.course,r.status,r.time]),styles:{fontSize:9},headStyles:{fillColor:[37,99,235]},alternateRowStyles:{fillColor:[245,247,250]}});doc.save(`PGDAV_Attendance_${new Date().toISOString().slice(0,10)}.pdf`);toast('PDF exported')}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('attendanceTheme',document.body.classList.contains('dark')?'dark':'light')}
window.addEventListener('DOMContentLoaded',()=>{if(localStorage.getItem('attendanceTheme')==='dark')document.body.classList.add('dark')});
